<a href="https://colab.research.google.com/github/A-S-Adithiyaa/5thSEM/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

In [4]:
train = pd.read_csv("/content/drive/MyDrive/emnist-letters-train.csv")
test = pd.read_csv("/content/drive/MyDrive/emnist-letters-test.csv")

In [5]:
print(train.shape)
print(test.shape)

(88799, 785)
(14799, 785)


In [6]:
train_data = np.array(train.iloc[:, 1:].values)
train_label = np.array(train.iloc[:, 0].values)

test_data = np.array(test.iloc[:, 1:].values)
test_label = np.array(test.iloc[:, 0].values)

In [7]:
print(train_data.shape)
print(train_label.shape)
print(test_data.shape)
print(test_label.shape)

(88799, 784)
(88799,)
(14799, 784)
(14799,)


In [8]:
train_normalized = train_data / 255
test_normalized = test_data / 255

In [12]:
train_normalized[:5, 500: 504]

array([[0.08235294, 0.00784314, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.01176471, 0.        , 0.        , 0.        ],
       [0.01568627, 0.        , 0.        , 0.        ],
       [0.54117647, 0.03529412, 0.        , 0.        ]])

In [13]:
train_label[:5]

array([ 7, 16, 15, 23, 17])

In [16]:
np.unique(train_label)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26])

In [19]:
num_of_classes = 37
train_label_transformed = tf.keras.utils.to_categorical(train_label, num_of_classes)
test_label_transformed = tf.keras.utils.to_categorical(test_label, num_of_classes)

In [21]:
train_label_transformed.head()

AttributeError: ignored